### ISSUE TITLE
GUI incremental mode 

### ISSUE THREAD

**Issue by freemoore** [PAJohnson/odrive_gui#4]
Hi, 
Using the GUI run on a raspberry Pi 3A+, from the file OdriveGUI-armv7l.AppImage.
I want to explore mode Position Control, Trapezoidal Trajectory, incremental moves, but the line: odrvN.axisN.controller.move_incremental() only appears on the menu visible when you click Add Function.
Selected, that line appears on the GUI, tinted blue, with no way of entering arguments and has no effect that I can see.

**Comment by PAJohnson** [comment]
Hi freemoore,

The GUI does not currently support functions with arguments. It is still in early beta, so that is on the development list. Also, can you post this issue on the ODrive repository? This repo is no longer active and I will delete it.
